---
title: "Tourism ~ Year  R-squared"
output:
  html_document: default
  word_document: default
---

##1. 加载包，读入数据  
```{r message=FALSE,warning=FALSE}
library(tidyverse)
library(skimr)
raw <- read_csv("outbound_tourism_china.csv")
```

##2. 查看数据概况
```{r message=FALSE,warning=FALSE,results='hide'}
skim(raw)
```

##3. 查看各种统计方式包含的国家数
```{r}
raw$SERIES %>% table()
```

由列联表可看出，TFR统计方法包含的国家最多，所以选择TFR统计方法进行建模

##4. 选择TFR统计方式，筛选出TFR统计方式对应的国家
```{r include = F}
raw1 <- raw %>% filter(SERIES == "TFR") %>% 
  # 增加国家列
  mutate(country = X1) %>% 
  # 删除SERIES列，change2016-2015列
  select(-X1, -SERIES, -25) %>% 
  # 将国家放在第一列
  select(country, everything())
```

清洗完数据形式：
```{r}
head(raw1, 4)
```

生成国家列表
```{r}
cnty <- as.list(raw1[,1])$country %>% as.list()
```

将数据清洗为列表函数
```{r}
tidy_list <- function(country) {
  num <- match(country, cnty)
  dat <- data.frame(year = 1995:2016, tour_num = t(raw1[num, -1]))
  return(dat)
}
```

将数据清洗为包含52个国家信息的列表
```{r}
dat <- map(cnty, tidy_list)
```

创建建立线性模型，并取出r.squared函数
```{r}
mode <- function(x) {
  # 线性回归模型
  mod <-  lm(data = x, formula = tour_num ~ year)
  # 模型摘要
  smy <- summary(mod)
  # 取出摘要中r.squared
  r <- smy[["r.squared"]]
  return(r)
}
```

输出r.squared，country
```{r}
r <- lapply(dat, mode) %>% unlist()
country <- cnty %>% unlist()
```

输出包含country，r.squared的数据框并按r.squared排序
```{r}
df <- data.frame(country, r.squared = r, stringsAsFactors = F) %>% 
  arrange(r.squared)
head(df)
```

输出散点图
```{r warning=FALSE}
ggplot(df, aes(x = r.squared, y = reorder(r.squared, country))) +
  geom_point() +
  scale_y_discrete(breaks = reorder(df$r.squared, df$country),
                   labels = df$country) +
  labs(title = "tourism ~ year  R-squared", x = "r.squared", y = "country")
```

